# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_fram.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 269)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/查看.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 631, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/纯色背景图片/Snipaste_2022-05-23_15-15-43.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size:20px;\n"
"font-family:\"微软雅黑\";\n"
"color:white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 20, 221, 41))
        self.lineEdit.setStyleSheet("placeholder:\"请选择您的文件\"；")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: blue;\n"
"    color:white;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size:20px;\n"
"font-family:\"微软雅黑\";\n"
"color:white;\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 80, 221, 41))
        self.lineEdit_2.setStyleSheet("placeholder:\"请选择您的文件\"；")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: blue;\n"
"    color:white;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: blue;\n"
"    color:white;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 160, 171, 31))
        self.label_4.setStyleSheet("font-size:20px;\n"
"font-family:\"微软雅黑\";\n"
"color:white;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video_Frame"))
        self.label_2.setText(_translate("MainWindow", "选择输入视频文件"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.label_3.setText(_translate("MainWindow", "选择图片输出文件夹"))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_3.setText(_translate("MainWindow", "视频转图片"))
